// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x97XLbOLLoq6B4btVJ7pFkyR+ZWZ9K1XGcTMazceyynOyPTSoLkS0JYxLgAqBszZar",
	"7jvcN7xPcgsf/AYpSpYdZ0d/EpkEgUZ/odHdaPzL81kUMwpUCu/4X57w5xBh/fNkBlSqHzFnMXBJQD/2",
	"OWAJwYl+NWU8wtI79gIsoS9JBF7Pk8sYvGNPSE7ozLvvqU8CoJLg8BMP1We1FiQo9ZYkJHB1JCSWiYYC",
	"aBJ5x3/3KJN9n1EKvgT1yS0mktBZf8p4Px9WeD0POGfc63kzLOegOuwTStTLPqELoJLxpdfzkrgvWV/N",
	"xut5giXch/6MUfC+NoJzRqfMOakkDtbF1AK4IIw6urvveRz+mRAOgZq3xo9FRwmQKrZ7BYIVQcrHymfG",
	"Jr+DLxUcmvaXnN0t6wwwlzK2dIwI/QB0Jufe8ajn0SQM8SQE71jyBKqz63l3fYZj0vdZADOgfbiTHPcl",
	"nuleFzgkGu3HHouIpCTsJTzsCYm5FJTJWyLnr9XQQuNC/3piKCogUJYh6HEhiPDd69FwOPTu1bB1WgkB",
	"QkTbEtaOokhxBE6uZ7cU+C+EC/nRNglA+JzEUjO2d6He/6dAU9UE6W56Db18wKs6CXFLH4LiWMyZUWxE",
	"QqR//C8OU+/Y+4+9XPHtWa23N7ZfeDmeMed4qXvTyuCso6LSja/141xZFRUNX0jGtGIybR0KxiXydq6F",
	"/ssCns/5ayur/MJ4VGeXHMAViDrLGjayQnc+TyfZwxl433Sf9w9De5llxvodYlMk54DyoVCAJT7+QtH/",
	"Rv/I5v8P1EfnmCY4RNkzlMQhwwFaEIx+G198NJ9gpSlV81MWhnoVQpMluoiBjudkKtE5mXGsQEAnwYII",
	"xpH+4gv1eg9HGKPApq9zCHXXRk0UOafONO3M8YEI2VlmCurHITX52yvD8G7Gm5LQQbJfSAgp1qcKc2Wi",
	"eb2cIyaEYi1XD8WpUe1OpaNUUZ1/tkHHOuO7KajR1E67T7HpvAq8ea7QGNXnMPB6FYI8CwzUpnkaJkIC",
	"vzJfqdZC/QbDrmVY7QsU42XGQD4O/STEykJEvukL8UJnNTTYRkb9lPs/e5tiIu1JsmwAKHWrxt4Wa/qM",
	"Ss7CyxBTOL38VIfr9PIT8hkHgWLgyDZHsWqPKAsAvQhgipNQHqNXL3OoCJUwA76meQJRLJe9iNDX+9pM",
	"2ddWShnKc4jsilIG1DxHhKL3b1bDOtomsIca2KPRfg3YjyyAU5ZQB0N9TKIJcEX0OqDiGI0Q4+igAPGB",
	"Atgu/aPewdetQG80/ggd1CAf+3MIEmt4VmE/CUN2i24Zv9GyIExbJQaMuqZTmMYUhwIKuJ8wFgKmel8X",
	"JxcL4Kcsioi8UqucGVl/6R17o+NDr+dgT7YA3vf1V0gvjugFDGaDHvqiPvniFRDnjY5HXs8bHe/rfw/1",
	"v6/qxpLCpfqkv8BcKRChvj2NkwsK1+yCKuWZ/nV9ywp//cISXvhzTO5U5xuJ5pwJCcFpgSYOrTFFelNQ",
	"QToRyHyN4E4CpzgMlwN0RtV6iyWZhIDU7qPy1ZRAGHSkVaSlbQW59mvkskLaSrH9dop1o5UZqECuwgND",
	"scIDTbRNyaSkALgW9NX60zTWQvEQ9ZOtc3VVmYOzQlG+eP/m5aPBVNaIOUzXcw44EG3aUCFMmmZV8NAL",
	"teqOz6/zlZfRlwN0NkWUSRRztiABBD1lTCQRCESZbv0i7e+1IcXLATpPhEQTQF+S4fAAXqMyFXtehO9I",
	"pBhwfzgc9tSO3P65/RVuWLfPcjvBqRWbxK/KjA5u+NrVDBIxo8KhcU4ddk6RHIiDSMJm22dM/lBCu2IX",
	"cFpqfN/Lt5LXTOJQdN5Q2uYav2bDcsqoSCI7nRX7dz38lePDBoJZeN2D1SfRQowcTRVPxQI4DsPMSBS6",
	"HRJJFJkNSwXpFVtErGmH1BXCfc+bYhIqDb6yw7ShNQJwEIDdeS0wCfGEhEQunUNIhSCnPtWoQ7lWxT5n",
	"QiCFk2aIdXdN+tD0GBW0Yvc+G1BguqQZIqwRZFXZf5Ux/dLZfS65rSguaEcXmBU2LcBcHqHn4JQqoQtU",
	"KWPUycYsikO4I3L5loibsaLVOypd6L+ggEC9Uqa72v8ERNwgP/seTTjgm4Dd0hp3C9WtQ0Xl3+oWaMpZ",
	"hEZqQ3XYQ7dz4IBGykZSo4WAhUyHM2NPGZMxJ1QiTAN0mLaMWN5wgPSU0OjYrCD+69EQXb8xS5AgjELw",
	"33bw/azJvmqSPj7IHh8VHx/ax6CfDop+nSrvjckfcP2mifkKkCAhGcczUAi+fqMF8PO5QFgiOSfCDFx0",
	"fgQsUVZ/NrDhYx1PiFZuZoo9+xVCrGbQtFk6UHmq7Yx2Mf6Io85cFgPvX4z7ymB0Mlvdh8GE23l8PQd0",
	"MdZuYwR32JfhEmGBiEQ4jgFzoYZcRGLAdEjFmLroi3cFAfoVS/SOSuAxJwLQB0KTO/QX9OLVYX9C5Msv",
	"3suBw7V33+vM+lgIMqPGi3gaqr+my4vxAA3Ra5RQ3zwhymYaoddlYeihQ/S6zPUN7NiRLXhCqVqsNG9c",
	"jAer2cGivFfji1WcsJbCuRg/groZVtUNDYiPJbi0zsVYNY60axe00hkW2mOqG8yx+iAJA23rTgDlxHsg",
	"XbYnri6yvMUSKwUEdTet0rbGF1bj7ykHOMUx9olcvn9TaFKY3hzz4BZzOPF9CEHhLjhni2LsoLBhVfth",
	"p99NBzenxKBD0Ua1tGTTaAnSCaiFAEuJ/bmODbfH5dQemQXgjk/HnEnmszANLdQamJV2xfxl09cLoAHj",
	"q6O+0gR8qoPVsJ/12EtJ1oz8yuRSLLg4450Oode4IgIh8MwhaLo9Sl+vim+l7b6qkYQkkd6evAWJSVjv",
	"2zyHAEHW1O5kjDhjJAidhZBtdTQ2KuycmNCMA3LTKQQobaNX4Uzq9L4DvYiZMjryEQRiNFxqZ8gdVrLp",
	"HXsH88NhNBSuNSHCd28bQTg3G9p0fkVQXnBMZxCsGvgg2m8Yl9CWcc3OefNxf24algMWTmTfKbPaDMGm",
	"aM5utVgXCHuL8y0rBCs5yQ7kYuFfiZBsxnFkwIg5+LpLqxIq/IElLsXBmkQ6j3dFhH7GYQLu1kJC7HpT",
	"lYS0E/tFz0DinA8TrrB/nJyqzdYqt43ekTVrxgLkfpyMmX8DcmWfwjbr0itx6PdPlPwzAURyNZ9JnlL0",
	"Tn7W25pzh2mt0JPuFAlF52+KZjOh8tVhJzibF4aumjvTx83a1Sxs0pFxc0NoUMwjiDGXVHuy/ERIFumf",
	"HGZJiNUvHESEOhOWGJ9hSv7QQtWwjicCeENuR2VKWcueAbDWvXOSNlmqYuG1hMsJNQQzHpkyYnS8+z2R",
	"xqfmCHuo92hGtOUWEYnmWMxLyso/wqNXr0aHr47w/tFk9JMPAJOffgpG4B8OA5gc/RT8HODDwy7mg4bm",
	"s8mqcu88DDw28UpvQHpoggUEiFENpsSzEnjDwWhw2D8c9mcW0C5wzJoR8n47qGjKW3PP+vPD5tvOhflk",
	"y1A0MB/HDm1pXHPiEriyfX1Q+7s19X7J6ZvmYtUDC6qNn7VB2gs8QKfZ0qb2odq6QydhyPTShBanl58E",
	"2kPGTXA5Xwri4xCdWt3dwQuQGcTdM6HyTYBjskoPX7Jb4GOpNjxaEoOAqHni8LKE20bM5VRRvXUHTC94",
	"DTApClp3rHt5X2chrzjs3TS9OjlPl5dNSGs/TWlr/7TO1rCjj4eCvGX8pjsKP5oPXLM2OwsrD24cNji3",
	"cslpQrBq9WtKa9fed3vkc3lRzdB15i0gsCQpbgVSyI9zK5E2YegUAFGI1EJb2Q3E2uNvowg6bIokU4Yy",
	"4YUcNZsXVYN8kWu1taCw330jrRkwi1PT+yplXeitl2OsFdNvrQ1eTVS0mrx9MqpR98l/trMwzLiy9bmo",
	"zy8SOmqkxm2dVR4Uq6A0I6TmWWFt3yzHqGYBbRR3+XwuUlda3u82gzDrDKDwuDIe06lDl9Sr3teKg5zF",
	"i8NTRqdk5nB/mVSJ91jCLV6WMlJJvDjcRh4ciQ+/4SDgJun7SE8qoOLJxiLxSRBwEE83okgmFOQ5Fjdb",
	"ySE23X2LsLgx8fp6sD6fY2n0XpW+BvMuJvmNTeo8+wb7NzPOEhqg39nEJqwuqV9MW9Wp2s6dTNbG5fPM",
	"0zvR2Vt0OweqhzD+X2VIiMT3QYhpEobLotXQlCgNqSevxWGHyNRMRPvZmo8KlLv4jU3Q2VvXNtvlDkmP",
	"87Qp2t/YZGwath2CaSDTOBuiDqb50qZ+x0ADQmf/QH2k3hGB/plAAoF9i7mwby/NT3T1+ZqxUKB3dz6E",
	"aEpCME0tU9rWVzaEcnF5gj6fo/Qlo8K0zkioGp9UGKVCWPOFIUcKp/nLJIdpotpuMfUhLLQzHjT7UEcf",
	"MmeCmbjiSDMztZHK5qADzRZEG2DWP7K+nH6GD3hi/CUVPwYstyLjoe5eccOi4mt7eJ8VFlMgp8O4WCzz",
	"V+RBpY0zkqPM91EI7ORe0C0mJzv7t1nK+WY8YBEmtO//vJ3c5caUqc54bUpxOm9HXHOGU9b6jc56cEQZ",
	"iLjpC/IH1GJtoodYFpeMgdtQYggLCNGLUf/wZZZy0CVzIUsnaEleEMqS4xoLgaJnMWNA96YAPUYj9KKY",
	"4vCyh/azJ/v2yUH25Mg+ObRPTB7Dy4HapaIpS0oTEwhzQDi8xUuBYg4CqDSxzE4bz8YcE5dDpUCbi7HD",
	"ZThekyTDMkm6RndTwqwZ4DXoIwt4FPSV4uUrkef2yl2uyqdAFyVkBkRIQn2ZpU5MtalTtsr/U+R70QF6",
	"h/257cHHnBOL7bQDo0x6iEihTH3gxK/RFL0Y/r//838PX/Z0lF19TZ0pCmRTROYpKA48Kqkakz/gSivo",
	"NR1dleNnEkvio5CxmyRGEk9CQBGOYwU8KDwFmaqRBDjS65HiwzbsDNC1wj2jUtkMRNioiY9DvbjAAhTq",
	"7QqgEMhhGoIvDR3e2tllykXtetJYX0rXfMQY+zd4BqXchVxhM7EFJBV50qZmZNO4GBc5jgg3y/0VlkbK",
	"6owmisk+cg5Lm+5Tzvb5b6QX+7yTRs50Z+qgF45Mnf4heo0IVUadth3zvl4aEkY41mTEhIqKEqvJXVni",
	"eojDDPMgBCHS6GmE6TKVjkwyKhSrrsbVpbCmgevSUCS6U+e0Lux5iH8LBpMkETyOqZSP8XSWUs/Lxxpr",
	"neU4zmp0mQKWJ3SAPqueLO8eoy+pU7Ovwy1fvB764tmswj6bThU6v3g6EZ9FREqdgx+GyGpIzfyq27JO",
	"rWe9VPRljDmOWjSAceNWY3+mXSGrAOl+QNGCLYBzEoCwoh0lQqIIS3+Obii7pbWvrGs0zdmTHFMxBf5N",
	"reXfokksDC4Ubr7NWcLFtxj4twAvzXPJtZ9dzBmT3yJCzetFZN7GTKinliO+AZ0RCsDFF+/lAH0SwPsi",
	"ieOQQEoJJPENqKXehwCoD3o+aMLkHFlng9B6OdNg/QA4WWTfD9AnauZ5kyo2QUKgSouRGWW8kkvWJN3d",
	"bO2iSOa29ibebMOdpf6SUNYV/ruaka4manSq6cvovJScXbj6ZcMKlU3zTIjEkdyGS3UU6kVM0sy8pjSG",
	"2hdhugtud4qbZj2vdKDWb0zPK0+je9SnMn2H9KZxobrfcyFuifTnzlk2FoKQleoHQmIaYB6YlURyMkmM",
	"UyHrvuclVAkQ47LBsbAIcVPiwiISp00kcqfR0aY16qKQx+CI9LAoxnTpZpL1622UBMJVGsc3L+pH3Vcm",
	"AnQs5dGcXtKcSdJI9bWL3rRUubBpJSnCm0rZrCLhqf5qDUJuuGi3UnLDPh9A/bXJunEBCtszMv3eb7Ek",
	"SGMlhCKua4yyiiHWqm9RUgYOrVl8nxdf6K4yHlH+m/O4auhpWLCbEmOLC7YOdKTZtgZrNfs7z9Hf0KCo",
	"JQQ7944FYzD3+dXmGuE7HV9cnXtr8jUcmbCFWGchGba0Jzia7zfm/RK6CgCbhPsQAEZNANSzTcvQODDU",
	"K1DQJV3m9KPzdHn1MGTpGLnDJxsn7tSp2hH0btkxUfuh6o16rVrXcZKd8G3BzpX7PGt1y2saIT9vlRK7",
	"LQ/AibY8BYCbnbSJ4axGWkgiIsV6p20/mG9aUF5PGVgTLFbnr9XwVZnygdT7kKGmgXAWd2sSKPvqASxd",
	"x2/3XtdGSlopbSsl5zYoO1Y1Gwul1XIInJCbcmv17V9a7rK12NXM1rkq5vquyvN9kf6QePZSn+2EwATx",
	"Lz6f6Mis0qtq89rtmFJx7L9hTp3nzu2LYjDfjoxLwAVkOgUuzKEZP+FcvSw16QLS49UZJO6c3TgtvbiS",
	"WqZI433PE2J+mUxC4v8VVn752ZqiwXj8a/6R3mUWdsmtPWQNnfbWZpX2tKug+5bfhOEdNmtz8UZ6ySEi",
	"ouSuLxzK2+burqkuaQGGZvlt3NOpn1MdpzudY0I7E/q0+uG20L1JuZGALKDnrEjXjWk1irQLPs8PXoNh",
	"e99JvFxbvWYWWGsXZ7W+QxbMm8ad246fIEhd9D8wX9V5qCExzDzXJ4cRB5lwalzxafApFCbwHzD6nzJt",
	"weQcODKdi3ohgsYDsidonkSY9jngQEeEC6/TqJTJUjN/EYFUv3pPNljniOUJirA/JxQah7qdLysD6Hiy",
	"iTV+8X7BJEw4fPEsPDp0pNsb7BCBNKup5ubgNWXFo1v5oYYBOkFXGkzkh5iTKTEZFb9eX1+mk1WsjSaJ",
	"wrIuCiWzOBAictBeGdxJTovLHHk6uYFNj9EXb2xS7L54iPHiTAfoXJ8hp1N2jHTZ5+O9vRmRg5ufxYAw",
	"xX9RQolc7ulSLGSSqC34XgALCPcEmfUx9+dEgi8TDntGYvViThgVgyj4DxGD38c06Gd1vDs4aoyiajmI",
	"oG23s67G1VYN73Rol87+JMBxdHxC2Lb86BDZc+JZc/PE0XRarE7tCNu0vWR+5rJJHashljjyFASAtXmj",
	"UBFjv+MRzJVUiueMNoRYiAxhW7XnNzr5WZlOL0N6juMCRtO5FPC4arum+KbJ2Gvinq6ssIHD23R0385E",
	"G/r6mxlv0w4fxKwbhwP0EEgNgChGuvP7Tpy/cpvZIAkboqdFehpFYRshjIL4rCstTRKyli2sVbHDElbP",
	"m+zgpxO13GrtJGuPq7A3L9HbIATr63KXEZCeVKufiws6XR3iYqPP56kL800xWFO5+6NYPqP1mG7WMD3n",
	"1XIq9BfGTXZCWry4S7u/ETm3Ti7R/s1HJtu7dx0c85ywrQSkaVQ3xoU7VJjlSBur0nLvJmGzNGXvmgAf",
	"25KTtchZcaA0r3aydB9H0HnMPQSUE3+eHjwxUaosBV2nLeqGAzROYuACAhAoKAzzZpnn4A5cMbpiBZP2",
	"U5h1rrWJu1k2yIbfmypOG36cIn3LhKvhSbW7XsYgHjKQ6mDFIE7KrZvqWz3P/UA2RC+Grz/lCUM9NHr9",
	"DotlD+2/PoeAJFEPHbz+FfOghw5f/01txd6HbFEs39k4xThZRbxVqcyu2dg4ni6YTICjSaJL5eS1tIf9",
	"Q5PUdtT/2fz4S3/0yvwa/dQ/2Dc/D/b/y5TcXjENE+N8xJnYIOrKybjmcNB/Zd+/OuqP9u18R/t/6e8f",
	"2eb7R6+6TfQj8TNp3+Y0J0v08ewU6WS8wsQsqBZIOx/z32ETwBkbF9esLSXu0cL0N9BXtLhSGdfMNqFj",
	"4qF6wnHYIK0jtInKs1+7NF28taomHEcbLyCr7KVOxtLalpJqNp5jDsFbIm7EqiKU2gs6xwtAWNoDVIwC",
	"EroHbQx0PKLv1WdVWP9TTGZrcnFxLxOsgZNdsuc0xxpd949+w5sPXJrjzW0+9wdsRvPdiWG3/H4tt8v8",
	"0WcsxPzbjfXNu+JWWykFUJ1q1JjhrAscrPKB5pUh7ptMsarJVhuoQyHo3I7Oyz9rT7taZrda9jk9SWU7",
	"7iKsFvT2CrJVm3KrWNAvbAb39lDRoM30YGnoJa2+2o6m7pWw81WsugVsPGmQZ8c3hOdnHAdwBT6LIqAB",
	"bkoys+8hQBdjZL/SKD6//owKSfj5OVdM0QTSpvr4MUbFZitD/77FiivBv7AAczCn6voJd1QQgLuYcBDf",
	"sHSWESXF42Bp6ZxPVx+QZDegI2YdXeHcUXH2kkPfnvhTXaru07wdUyQbkE0BC4jwmT60SCI8g8FK3Kjx",
	"6ti4N+kvmkNC4oM9j2Mck95JjP05oP3B0LMAe2mQ6vb2doD16wHjsz37rdj7cHb67uP4XX9/MBzMZRQW",
	"3E6tJRhPLs8K98UeewkNYEooBJqLY6A4Jt6xdzAYDka6joSca2rt4ZjsLUZ7+ckW/XgGDup9IEKiYkPd",
	"M8+8xbrBSel9dkpMeMd/d9wdqA+95l/oM0WGQLpAiVrYvX8mYHKpDVKz2yZ79ibkDgGa+6/6+hB9XkrP",
	"b384TK/ysCllOI5DYvyQe7/bAG3ef7fbFbWL9752zsC7+KuiwuFwtLUxTZlnx1CfKE7knHHyhyH90RYn",
	"2jjoGTUXYpnyJmbp1Yv+34snpr5q4911iNQEjxCm5RsLy8xlGp0UG9jc1DcsWD4CNfU1mJXIgLKs7mu8",
	"NHqE0V14NigIDDM9AV3f4AClJ393DOx9Vc8dCnPvdzYRe/8iwb1h7RBct3ue6nI8CKPf2aTO3Prlb/pN",
	"q87Mj0KbbrSGVNo8V5BaAZZZ1qkqm4o+PaqyVFNs0ZB/EqY+HB48/qC/MD4hQQDUjHj4+CN+ZPIXllA7",
	"xb88/oBqrxcSY5Z+b0Wh5FEtcU7T6T1IXagtSyMqi/97kDvZ38n+v4vsPw9RbFis01v91ca1szVqzl6k",
	"9QSnJARTOHLOGWWJ0BUdXeaq/aKj1RoloSQx5nJPCWo/vdtiXdOxeI17J/t1/7FF/MT3IZYQ2EqH/s6O",
	"fV4yscp2faufr9igmUYlVu+4nJU6fcCq9l03/7ulbbe0Pbk/pdHY1K7OGHxd3qxNat+D3InsTmR3Ivtk",
	"LtDEIbImp3fFAmsaPVdpfUxXrE157mTM7hTFTlH8CIpiDHwBHL3byOOsDPY9W2ikbyUiC941bGvz0uK2",
	"iGbxO1MiqD0Ak3aQy4W9CuiqCMC/uVJyTDkTzadVT05IbE1Il6/URfWsVCujhXsMdortx1dshYsqKJOm",
	"LvN3s4bUsE+AZaVSiQ/oE83vZ9tMs2Zp7P1CxeIOqnXF/RB1LVuoFtWgbR3XLPy4OjYrfVaq91woznzf",
	"68gELbd6PLEebrsHw8Gkq27C2KnhnRp+HmkNWhVmGm1jTVgp/L6Opekoe/1vrPtcNeX/Xq6n7X0tVnCv",
	"V073jkfD4bDnqJ3uHb+6X1+51m8A2JpyLaCjPMVqLdJLJmQ/15qnc/Dt0YesNqd3ZMtopsVVlHzppOH/",
	"Qa+GgyGKCBXmDo89NBqirCo8UuMSOkM/o/legJe2Uqo5LcmmaKQboAAvhalIowuZ5/mXFTAO5odVQBQ9",
	"BsMhev8GYYle7Q/R+SQW6MX+voZq72g4fP/mpZbNetFT73B+YDusFyTNXuraKqUK6z8CDi9yUCN8V5jW",
	"wUG0n0658Phn+9SF2f9Bw8FRf3+g/tgTKJULZG4HwkIkEQgkzEUjZnh99smcjb3r+yxeIqDKYAyaSDGa",
	"7xcAq749MuA9UMS6WA0FTbrbve3MhudhNphLjcxxY2dM6kpX4TIFchUFzR1IEgKUCH1BUMzZlISgi1Zh",
	"FDIfhwj75lgn3BEhRc+W8hJplUz1pb5NeYAu5Bz4LRGQtcFILKmcg1CcgjjMkhBz/cnAFQM7SyfwiBuF",
	"bIxdiniJp3x7k0aJoeyhisYAZ9thiEJRMyetVd+PSWd9dLWJxt8b3RqzJVwXq/6sOv0Rhqjc3HUG5KLS",
	"osspkMmy1DGy9wW4ToDYVzmKut+Kcd9rHt7cYuNjAX1CBVBBJFkAUp0SHJobjV42gGRrBeUgrTGuvXlg",
	"06HzqzeaR3/McHrt1oaddnNrt9WnX4oC0JBQeFFu8hgRDse9LE98CqZ8n8fuHMyzXaVLS8EaWYStjG6a",
	"VRi9o8+n0vGPlZi0iu2/oxZ9qlg8ej5ZOwW93WiEVlhZreb63GrN5Nxx846bn40V0p6A1qqbTbPnzM2P",
	"aw99n0S0rqL0p/H5/XnFt9X42kuEFsK2HbxugghdKerVjfwn3fefY+3K6vXu1q0fiPH3/pWWbW7dhlxB",
	"xBaAsPEf64N9q2TBfFKVhmckDDX30ieLiRSCxMDrGLlQ6rp5/I7Ct1uWdlZlKYwVBKmcSbZSyk6CYCdi",
	"m4nYjt2/12JkylGJtgUnsH4v5LMwBD+tXpt+6fZ/jbO3j2bl2PuVdv76IpENVZrdPtqIbiKdevkUhMsv",
	"V9sRr4F47bEWS8GGIMs4ffkY7oTS5YhPHFhJr9jbhVSeFbfWl5POsZQmRi4uIt2NqKyzH2u73szWu0Oa",
	"u0OaDxpwDcugXnahQTbfg9wJ5k4wd4L5aLZfS4SrQSbN2+cmlo9lfX6fMFazNjDwZApzpxl2mmH7dRVW",
	"mdt7uhK8vkIPzLmU8gi/Ag601F98PjFV42taRDU5s2/aVUjw/Vb2loW4i3h0YufV7LeSXdYlr6HICuqm",
	"Vxa0GnAZfdGCYPTp6kOzBffW3i5gGrWS3HyASPDDWXHlCx9cOk1f35BdtVAQkF385yl2JitZv3QVeYtx",
	"VLwp3GUfnRXe/9uaSNWpPlMrqUCsnb20s5eexl7qkGCEw9AkGTmjI52yiBqOBDVeCVO74f4BUd187ML9",
	"965BC6/rJ5G6X1/9p0xk+nEO5aRRfVeYyCYoPMoaJIB/nxCRuXl+FyD6U95h4cxwWCe3LgtLOcXGvO2S",
	"1/N9cmseVYB2qTrP7vSOyUybLFGBiWob/R277tj12RzPcetV8/a5MOrjWEPfJ2SxSjp2rq0/Ra7nHHAo",
	"5437XvMa+XPwb1wxgVALVjdffAEGO+pXDbnQ23Qj0+Yq2T3v/uv9/w8AAP//z1xtNh3uAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
