// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbXPbuI//KhztzezdjWwn3bTd8UxfpGnT5jZpM03TfdFmurQIW9xIpEpSdnydfPf/",
	"kJSsJ0pWHpymu36XmBQIgMCPAAjpuxfwOOEMmJLe+LsngxBibP7cnwFT+o9E8ASEomB+DgRgBWTfDE25",
	"iLHyxh7BCgaKxuD5nlom4I09qQRlM+/a148QYIri6FxE+rHGDEoq1NKUEhchqbBKDRfA0tgbf/YYV4OA",
	"MwaBAv3IAlNF2Www5WJQLCs93wMhuPB8b4ZVCJrggDKqBweUzYEpLpae76XJQPGBlsbzPclTEcBgxhl4",
	"F63sHLEpdwqVJuSmmpqDkJQzB7lr3xPwLaUCiJbb6CdTR4WRurb90oaVWSrWKiTjk78hUJoPs/engl8t",
	"mwYQKpVk+xhTdgxspkJvvOt7LI0iPInAGyuRQl0637sacJzQQcAJzIAN4EoJPFB4ZqjOcUSN2scej6li",
	"NPJTEflSYaEk42pBVfhCLy2NLsxfD8xFjQXGVwraLAcxvnqxu7Oz413rZZt7JSVIGd+Xs/Z0RYZjcFo9",
	"XzAQh1RI9S6bQkAGgibKGLb3Xo//KtFUT0GGjN9C5RivIxLhDhoJiJhKbeNGF1RBXMEOAViLBoRqd5Ah",
	"FpoMgQiU29+zH7AQeGn8n+FEhlxVyf+XgKk39n4ZFcg6ymB1dJY94aRm0OaoJxKayR/Nz4VEZSQTc8W5",
	"QT471yGRC1MyZZboVxGkkLmq4ItOyzzkIm5aZ8HuGrUdrSa2Wl5/t8pF9vGKva+aph9T9mI39zajnTts",
	"SdVez8wY4lOkQkDFwohghcdfGPpf9NdKG3+hATrBLMURWv2G0iTimKA5xej/zt6/s49gDdN6+gGPInME",
	"oskSxXQmsF4YJRFmDAQy874wz7+70jgDPn1R8GVIW2Qq21LTjLoN5JhK1duLSojn8KNi9IN1AbfxTWnk",
	"2KhDGkGu6ykX9a3y/MIOJpRh42l31ak9TZw4p9GvaTX3sY/rjN+9n0Zp3Tt5ntil6qLY37VS46ZEQ40m",
	"le15hPpoCP0KKywVF9C0LkLlpcWNBk5MBcABTnBA1fLNy9IUyhTMQOg5IRZkgQXsBwFEIDT6nvB5GfYm",
	"nEeAmZnMpbJrVZV1ZMLAKQWRq0zPRIsQBCAVUmlM2giAqERYKRyEJorujmCufS/mBNyRfCK44gGPchxs",
	"HqJc4Wid/Krt6TkwwsX6+FjZk6u+WEP7K4p+vmXtyq8Jl2vB5Q6vTbLRsIoYpMQzh12b+SgfXndQ5/Mu",
	"rn3vLZWKzwR2IJwBrDKmtum5wM6Ysk84SsE9WypIXCN19nIi2RO+5cSlp7dcuqLWJD3gIhOi6v9pPLHm",
	"fHB6jgIzqdVcS5wHSXrGg0tQa2nKbFofqtThdOeMfksB0cL39DFivE17nytwiCHmYnnysklMqwfZYUQZ",
	"OnlZPn8oU8/2evHZ7q193WnlJO0mn6fBVQlOGrEIZVYCPV4H/RlVBzyOqWoSekMVCswYCrEMddx+heNE",
	"i+0FT/Hus2e7e8+e4idPJ7vPAwCYPH9OdiHY2yEwefqc/E7w3l5Hxu1OMz7ZQZNh+GiCJRDEGZpRhRSe",
	"VXjYGe4O9wZ7O4NZxs1aLy6ErXLRolyBHY4SpVKBkKcg9FkUAFMgbujyqzOgfxZTnHsOetrKT/kCxJnC",
	"yhLFhFCtURydVthvZa4QXFPrz5iBkxaetJIOrL5uqCEGasHFZX823tkHXLTsgZRtW8vyekqxnV2z3uba",
	"aY7P49sKXD9Ji4Xq7DcV29z+kvoqtua28lI+WE8VMwfoThP1JC184Qld8z8d2GlWXWtnn8gmLmYLWQJ+",
	"xqZLtmM8sRhclesSlveSy0aGvGZvXju/706zJrNmOV/GJekK8o+kTB2hMa7Uq5rFYp5WRhrnbeOJKFdt",
	"N97aab5XyRvsauvF6O/8NfEdGJDDQzNgm8sFVUHolLK14KZqRSCpMCNYEBvSKkEnqa2Nr8j7XspkmiRc",
	"6AFXpWseYeZMX9xhNms7t85CHUcXCTl8S8FGfJzB+6k3/vy9Qi+VII6IDmyrv3MxMz9f1CMGO+CsvltS",
	"ThGafOZ1uXupoN6irFUvxZUKeQUHTg3b4l7Ty/Lbm85CyiyroWyuTny7Gp/x1f4+Z8HVdXS3VqnZqYCY",
	"ykogUsqpb3x301FLbbuAKfHQvrMH5mGHXeo/pzTACg5CTNna0ysDeHJQf/C+1H2ziw2IE7X0CZ2D76yD",
	"9ZLFqshEzbb0cLXsZfL24kZntDI8TScRDf6AZf9Vz94WDzkLZe3beaM6Z+bbDru2I0WpbWsbDVneJzbl",
	"eCQ20rSH1V127arA/G4KckiASgVDJtYydYQAR5FEKsQKEc5+VfkMrkIQyBKXzWJqa91pH4VpjNlAACZ4",
	"EgEqDedFQ3u5bP+jEmm6Jr4ZuuBeAJb2/rq+UIyDkDJoXWoRLmsLaB1QZnj44h1iGqUCvngZP0N0lDFk",
	"tUMlMmajp9t6JuPlWgPCc0xNnWSI9tEHwyYKIizolIJEmKG3Hz+e5sJqM0WTVGsZNCWF+ByEoAQQVcPu",
	"1gTndma6LJSH3jNAfDpGX7yzNAhAyi8e4qIs6RCdmNIsm/IxMvfO49FoRtXw8nc5pFzbX5wyqpajgDMb",
	"53EhRwTmEI0knQ2wCEKqIFCpgJH1PnPIUs7kMCa/yASCAWZksGok6BEqWdDpSNVM5HG0ueigI1TKl3bh",
	"b57sNVNL0qvdwknz5APYK66XAvAl4Qvm6JcoV2g7qxeriXl+35H6H3JhMw1b+us370+qwj+xYJTNZPcz",
	"77jqJl9TUCFkzrqTz7VMtXHg1r7srh13Z/PNrbu2lwAHeQZ6y+ftpcYtHl5d3Jb36J6STkaDu8jFyrth",
	"0fM+ueM3rBMSSAToMIXUqt6FdfBVY1Yb2S6Ws6ddAJjcW3FT4PjWtrIOH3qBQ39kcBUFveZSfuF/uXgr",
	"nyg7l9nxqipbbMzlFU4waI1hN96fpcNtWxrsCj7vUJErYmJrCG3tKu7oc+PySxl+vczCXFdqdh+1yG7B",
	"C1+vHQbttcSi/uXI/2vWHmQ266qZlXBBgKQzBmSQCkelF64SKkB+xY7Lrdd6zIapisaQXRkCOv9wjBS/",
	"BBNr9yvLZGtX6Z8KGFjeDElNXuNIxDGhbGajfNuhRKgMdKi7RDTGMxiuLXTo9ZrauDaxnd2SiAbAJBRN",
	"Hd5+goMQ0JPhjpcx7OXh7WKxGGIzPORiNsqelaPjo4PX785eD54Md4ahim2GSZW5eivuGE+zO8b906NS",
	"g+vYSxmBKWU6jfQ9ngDDCfXG3m/DneGuhiGsQrNHOkgezXdHRYnYXkuCY890Jo/KEw3l7Jwj2YT9yrgA",
	"mXCW1Zye7OxYE2Uqq9ThJIk0blHORn9nWZQ9Bfo3RJn6glF/rWHyDy363s7uva1pWxwcS50znKqQC/r/",
	"Vt9P71HQ1kWPdGzPcIQgm+F7Fk4+l+v9F+b4lo7dtGU2nQZWrgeqO2on7ZcnCFvRfsnJcgO7aTrXtCxx",
	"GimaYKFGGgUGeWfHTemVG+Jq9zr6KLhumOjuBoRybZ/VLLE2+gDm8hITlF9GbP3Cu9C/O8Bv9J2Sa+ss",
	"pim64TavzO9r3MZOqrhNggWOwd5uf270rb1ytvjpUM5AdV5ZH9sqe9WG/ZLG1pQfri8eBJK74PhfYup7",
	"O79tftFDLiaUEGB2xb3Nr/iOq0Oessd4yjlDljegbKyXQECnFEiX174BtXXZrctuXfbBAtNUtXbNdx+w",
	"dtJj9dZNBsjZDWivWHYLFFug+BmA4gzEHAR6feuAfWRfZRx/b8l1TVPWGkipNW790xGlpU/tgXPkrCXA",
	"YRwFa8hsLkHSXhpP0yhabvFmizcPiDd5Ybc1x4jXvPTRSDSyLxds7MC2d3ltR/WPjgONPisatsV42VV5",
	"IVnlBQX21d+siyZ/0l2DOVuNbkzV7Rj2Ly5B52/gtyXm5i6hbev0YLFxncew6QPiEVqEWIF2an0iE5ji",
	"NFJIQMKFPj94GhE0AYQJAYIUN7MEyDRandnfUjANNfmhzYIoJfA1I+WVT+zG3dkmU/RSE+XWwlosrPuC",
	"IzOzlruNs3xwI0FWuaH5oUOrrJV2e/XwqKy1eeb1vnJoM+TySdc/bVkR+7lKlu1mva1CbLOCOy14g/Cl",
	"ea/Q4ptvQG0dc+uYW8fcWOzXcYfQ4pN29LG55aaizx9zYdCOBpafFWBukWGLDPdfyFsXbo9Mr6d5VwWw",
	"45s2bwET4/XvP+3bvtAGiugpR9lIN4SQH3eydxzEfdyjlzmvN7+15nLT7bU7smZ386bkzgButb/mO4Pn",
	"H47bI7hXWf+wndS55dnHD81O/VxRXLWl24VppkF71UxdcpB/F5Lv/aDMZK3pV15T7AiOym8RuuKjo9L4",
	"PzZEqov6SKOk0mZt46VtvPQD4qX828prQCWvUaJJ/v1eymYIM/Th00f9PJrSCBChAgIVuZBHP5L37NPo",
	"J0jP1r6n0OcbvB9DqGrov19fBRD9T4+P79bfTmr5Xu3941rr9xbWvlHv8MHiG8TbRo8t3j0w3oWAIxW2",
	"pgp2GAUhBJeuLDAyUNMv+yqxkK16YfiXhlGLcPb1wJF3fXH9nwAAAP//L5w+XKxkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
